[elasticsearch]
url = "http://localhost:9200"
index = "browser_history"

[mongodb]
url = "mongodb://admin:password123@localhost:27017"
database = "history_db"

[server]
host = "127.0.0.1"
port = 8080 