[elasticsearch]
url = "http://localhost:19200"
index = "browser-history-index-v2"

[server]
host = "127.0.0.1"
port = 8080

[cache]
enabled = true
redis_url = "redis://localhost:6379"
ttl_seconds = 120

[database]
url = "postgresql://app:password@localhost:5432/history_manager"