version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: history_manager
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./history-server/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  history-server:
    build:
      context: ./history-server
      dockerfile: Dockerfile
    ports:
      - "18181:8080"
    environment:
      - APP__ELASTICSEARCH__URL=http://elasticsearch:9200
      - APP__CACHE__REDIS_URL=redis://redis:6379
      - APP__DATABASE__URL=postgresql://app:password@postgres:5432/history_manager
      - RUST_LOG=info
    depends_on:
      - elasticsearch
      - postgres
      - redis

  kibana:
    image: kibana:8.11.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "18180:80"
    depends_on:
      - history-server

volumes:
  es_data:
  redis_data:
  postgres_data: 