version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  history-server:
    build:
      context: ./history-server
      dockerfile: Dockerfile
    ports:
      - "18181:8080"
    environment:
      - APP__ELASTICSEARCH__URL=http://elasticsearch:9200
      - APP__CACHE__REDIS_URL=redis://redis:6379
      - RUST_LOG=info
    depends_on:
      - elasticsearch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "18180:80"
    depends_on:
      - history-server

volumes:
  es_data:
  redis_data: 