version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  history-server:
    image: history-server:latest
    ports:
      - "8080:8080"
    environment:
      - APP__ELASTICSEARCH__URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  es_data: