version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "19200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
  mongo_data: 